/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import alumnos.Alumnos;
import departamentos.Ciudades;
import departamentos.Departamentos;
import docentes.Docentes;
import funcionarios.Funcionarios;
import funcionarios.Usuarios;
import gabinetes.Gabinetes;
import horarios.Horarios;
import insumos.tipoInsumos;
import insumos.insumos;
import proveedores.Proveedores;

/**
 *
 * @author Gustavo
 */
public class menu2 extends javax.swing.JDialog {

    public static Departamentos departamento=null;
    public static Alumnos alumno=null;
    public static Docentes docente=null;
    public static Proveedores proveedor=null;
    public static Funcionarios funcionario=null;
    public static Gabinetes gabinete=null;
    public static Horarios horario=null;
    public static Ciudades ciudad=null;
    public static Usuarios usuario=null;
    public static tipoInsumos tipoinsumo=null;
    public static insumos insumo=null;
    public menu2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu2 = new javax.swing.JPanel();
        btnDepar = new javax.swing.JButton();
        btnCiudad = new javax.swing.JButton();
        btnTipoInsu = new javax.swing.JButton();
        btnAlumno = new javax.swing.JButton();
        btnDocente = new javax.swing.JButton();
        btnFuncio = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnProvee = new javax.swing.JButton();
        btnGabinetes = new javax.swing.JButton();
        btnHorario = new javax.swing.JButton();
        btnInsumos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        menu2.setBackground(new java.awt.Color(255, 255, 255));

        btnDepar.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        btnDepar.setText("Departamentos");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        btnDepar.setBorder(dropShadowBorder1);
        btnDepar.setContentAreaFilled(false);
        btnDepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeparActionPerformed(evt);
            }
        });

        btnCiudad.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        btnCiudad.setText("Ciudades");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        btnCiudad.setBorder(dropShadowBorder2);
        btnCiudad.setContentAreaFilled(false);
        btnCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCiudadActionPerformed(evt);
            }
        });

        btnTipoInsu.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        btnTipoInsu.setText("Tipo de Insumos");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShowLeftShadow(true);
        dropShadowBorder3.setShowTopShadow(true);
        btnTipoInsu.setBorder(dropShadowBorder3);
        btnTipoInsu.setContentAreaFilled(false);
        btnTipoInsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoInsuActionPerformed(evt);
            }
        });

        btnAlumno.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        btnAlumno.setText("Alumnos");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder4 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder4.setShowLeftShadow(true);
        dropShadowBorder4.setShowTopShadow(true);
        btnAlumno.setBorder(dropShadowBorder4);
        btnAlumno.setContentAreaFilled(false);
        btnAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnoActionPerformed(evt);
            }
        });

        btnDocente.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        btnDocente.setText("Docentes");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder5 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder5.setShowLeftShadow(true);
        dropShadowBorder5.setShowTopShadow(true);
        btnDocente.setBorder(dropShadowBorder5);
        btnDocente.setContentAreaFilled(false);
        btnDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocenteActionPerformed(evt);
            }
        });

        btnFuncio.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        btnFuncio.setText("Funcionarios");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder6 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder6.setShowLeftShadow(true);
        dropShadowBorder6.setShowTopShadow(true);
        btnFuncio.setBorder(dropShadowBorder6);
        btnFuncio.setContentAreaFilled(false);
        btnFuncio.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnFuncioAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnFuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncioActionPerformed(evt);
            }
        });

        btnUsuario.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        btnUsuario.setText("Usuarios");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder7 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder7.setShowLeftShadow(true);
        dropShadowBorder7.setShowTopShadow(true);
        btnUsuario.setBorder(dropShadowBorder7);
        btnUsuario.setContentAreaFilled(false);
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        btnProvee.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        btnProvee.setText("Proveedores");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder8 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder8.setShowLeftShadow(true);
        dropShadowBorder8.setShowTopShadow(true);
        btnProvee.setBorder(dropShadowBorder8);
        btnProvee.setContentAreaFilled(false);
        btnProvee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveeActionPerformed(evt);
            }
        });

        btnGabinetes.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        btnGabinetes.setText("Gabinetes");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder9 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder9.setShowLeftShadow(true);
        dropShadowBorder9.setShowTopShadow(true);
        btnGabinetes.setBorder(dropShadowBorder9);
        btnGabinetes.setContentAreaFilled(false);
        btnGabinetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGabinetesActionPerformed(evt);
            }
        });

        btnHorario.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        btnHorario.setText("Horarios");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder10 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder10.setShowLeftShadow(true);
        dropShadowBorder10.setShowTopShadow(true);
        btnHorario.setBorder(dropShadowBorder10);
        btnHorario.setContentAreaFilled(false);
        btnHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorarioActionPerformed(evt);
            }
        });

        btnInsumos.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        btnInsumos.setText("Insumos");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder11 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder11.setShowLeftShadow(true);
        dropShadowBorder11.setShowTopShadow(true);
        btnInsumos.setBorder(dropShadowBorder11);
        btnInsumos.setContentAreaFilled(false);
        btnInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsumosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menu2Layout = new javax.swing.GroupLayout(menu2);
        menu2.setLayout(menu2Layout);
        menu2Layout.setHorizontalGroup(
            menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDepar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGabinetes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnProvee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFuncio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTipoInsu, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
            .addComponent(btnInsumos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menu2Layout.setVerticalGroup(
            menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu2Layout.createSequentialGroup()
                .addComponent(btnDepar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCiudad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInsumos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTipoInsu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDocente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFuncio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProvee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGabinetes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHorario)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeparActionPerformed
        departamento = new Departamentos();
        FuncionesPrincipal.CentrarVentanaInterna(departamento);
           dispose();
    }//GEN-LAST:event_btnDeparActionPerformed

    private void btnCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCiudadActionPerformed
        ciudad = new Ciudades();
        FuncionesPrincipal.CentrarVentanaInterna(ciudad);
           dispose();
    }//GEN-LAST:event_btnCiudadActionPerformed

    private void btnTipoInsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoInsuActionPerformed
        tipoinsumo = new tipoInsumos();
        FuncionesPrincipal.CentrarVentanaInterna(tipoinsumo);
           dispose();
    }//GEN-LAST:event_btnTipoInsuActionPerformed

    private void btnAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnoActionPerformed
        alumno = new Alumnos();
        FuncionesPrincipal.CentrarVentanaInterna(alumno);
           dispose();
    }//GEN-LAST:event_btnAlumnoActionPerformed

    private void btnDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocenteActionPerformed
        docente = new Docentes();
        FuncionesPrincipal.CentrarVentanaInterna(docente);
           dispose();
    }//GEN-LAST:event_btnDocenteActionPerformed

    private void btnFuncioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnFuncioAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFuncioAncestorAdded

    private void btnFuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncioActionPerformed
        funcionario = new Funcionarios();
        FuncionesPrincipal.CentrarVentanaInterna(funcionario);
           dispose();
    }//GEN-LAST:event_btnFuncioActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        usuario = new Usuarios();
        FuncionesPrincipal.CentrarVentanaInterna(usuario);
           dispose();
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnProveeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveeActionPerformed
        proveedor = new Proveedores();
        FuncionesPrincipal.CentrarVentanaInterna(proveedor);
           dispose();
    }//GEN-LAST:event_btnProveeActionPerformed

    private void btnGabinetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGabinetesActionPerformed
        gabinete = new Gabinetes();
        FuncionesPrincipal.CentrarVentanaInterna(gabinete);
           dispose();
    }//GEN-LAST:event_btnGabinetesActionPerformed

    private void btnHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorarioActionPerformed
        horario = new Horarios();
        FuncionesPrincipal.CentrarVentanaInterna(horario);
           dispose();
    }//GEN-LAST:event_btnHorarioActionPerformed

    private void btnInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsumosActionPerformed
        insumo = new insumos();
        FuncionesPrincipal.CentrarVentanaInterna(insumo);
           dispose();
    }//GEN-LAST:event_btnInsumosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                menu2 dialog = new menu2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumno;
    private javax.swing.JButton btnCiudad;
    private javax.swing.JButton btnDepar;
    private javax.swing.JButton btnDocente;
    private javax.swing.JButton btnFuncio;
    private javax.swing.JButton btnGabinetes;
    private javax.swing.JButton btnHorario;
    private javax.swing.JButton btnInsumos;
    private javax.swing.JButton btnProvee;
    private javax.swing.JButton btnTipoInsu;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JPanel menu2;
    // End of variables declaration//GEN-END:variables
}
