package informacion;

import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import principal.nuevoPrincipal;

/**
 *
 * @author Gustavo
 */
public class Cursos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cursos
     */
    public Cursos() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        jPopupMenuCurso.add(menuCurso);
        FuncionesAca.isListar("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuCurso = new javax.swing.JPanel();
        btnEditarCurso = new javax.swing.JButton();
        btnEliminarCurso = new javax.swing.JButton();
        btnAgregarModulo = new javax.swing.JButton();
        btnVerModulos = new javax.swing.JButton();
        jPopupMenuCurso = new javax.swing.JPopupMenu();
        jPanel2 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCurso = new rojerusan.RSTableMetro();
        btnNuevoCurso = new rojerusan.RSButtonIconI();
        txtBuscarCurso = new rojerusan.RSMetroTextFullPlaceHolder();
        jButton1 = new javax.swing.JButton();
        rSComboMetro1 = new rojerusan.RSComboMetro();
        jSeparator1 = new javax.swing.JSeparator();

        menuCurso.setBackground(new java.awt.Color(255, 255, 255));
        menuCurso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditarCurso.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnEditarCurso.setText("Editar");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        btnEditarCurso.setBorder(dropShadowBorder1);
        btnEditarCurso.setContentAreaFilled(false);
        btnEditarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCursoActionPerformed(evt);
            }
        });
        menuCurso.add(btnEditarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 127, -1));

        btnEliminarCurso.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnEliminarCurso.setText("Eliminar");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        btnEliminarCurso.setBorder(dropShadowBorder2);
        btnEliminarCurso.setContentAreaFilled(false);
        btnEliminarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCursoActionPerformed(evt);
            }
        });
        menuCurso.add(btnEliminarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 105, 127, -1));

        btnAgregarModulo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnAgregarModulo.setText("Agregar Modulo");
        btnAgregarModulo.setToolTipText("");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShowLeftShadow(true);
        dropShadowBorder3.setShowTopShadow(true);
        btnAgregarModulo.setBorder(dropShadowBorder3);
        btnAgregarModulo.setContentAreaFilled(false);
        btnAgregarModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarModuloActionPerformed(evt);
            }
        });
        menuCurso.add(btnAgregarModulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 127, -1));

        btnVerModulos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnVerModulos.setText("Ver Modulos");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder4 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder4.setShowLeftShadow(true);
        dropShadowBorder4.setShowTopShadow(true);
        btnVerModulos.setBorder(dropShadowBorder4);
        btnVerModulos.setContentAreaFilled(false);
        btnVerModulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerModulosActionPerformed(evt);
            }
        });
        menuCurso.add(btnVerModulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 127, -1));

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setMaximumSize(new java.awt.Dimension(915, 598));

        jPanel2.setBackground(new java.awt.Color(69, 167, 154));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder5 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder5.setShowLeftShadow(true);
        dropShadowBorder5.setShowTopShadow(true);
        jPanel2.setBorder(dropShadowBorder5);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/closeWhite.png"))); // NOI18N
        btnCerrar.setToolTipText("Cerrar");
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCerrar, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder6 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder6.setShowLeftShadow(true);
        dropShadowBorder6.setShowTopShadow(true);
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(dropShadowBorder6, "Información de los Cursos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Gadugi", 1, 24))); // NOI18N
        jPanel3.setMaximumSize(new java.awt.Dimension(915, 522));

        tablaCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " ", "Nombre", "Duración", "Cuotas", "Precio Cuota", "Precio Total", "IVA 10%", "IVA 5%", "IVA 0%"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCurso.setColorBackgoundHead(new java.awt.Color(69, 167, 154));
        tablaCurso.setColorBordeFilas(new java.awt.Color(69, 167, 154));
        tablaCurso.setColorBordeHead(new java.awt.Color(69, 167, 154));
        tablaCurso.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tablaCurso.setColorFilasForeground1(new java.awt.Color(102, 102, 102));
        tablaCurso.setColorFilasForeground2(new java.awt.Color(102, 102, 102));
        tablaCurso.setColorSelBackgound(new java.awt.Color(69, 167, 154));
        tablaCurso.setColumnSelectionAllowed(true);
        tablaCurso.setComponentPopupMenu(jPopupMenuCurso);
        tablaCurso.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaCurso.setFuenteFilas(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        tablaCurso.setFuenteFilasSelect(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        tablaCurso.setFuenteHead(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tablaCurso.setGridColor(new java.awt.Color(153, 153, 153));
        tablaCurso.setGrosorBordeFilas(0);
        tablaCurso.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPane1.setViewportView(tablaCurso);
        tablaCurso.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tablaCurso.getColumnModel().getColumnCount() > 0) {
            tablaCurso.getColumnModel().getColumn(0).setMinWidth(10);
            tablaCurso.getColumnModel().getColumn(0).setMaxWidth(30);
            tablaCurso.getColumnModel().getColumn(2).setMinWidth(100);
            tablaCurso.getColumnModel().getColumn(2).setMaxWidth(100);
            tablaCurso.getColumnModel().getColumn(3).setMinWidth(100);
            tablaCurso.getColumnModel().getColumn(3).setMaxWidth(100);
            tablaCurso.getColumnModel().getColumn(4).setMinWidth(150);
            tablaCurso.getColumnModel().getColumn(4).setMaxWidth(150);
            tablaCurso.getColumnModel().getColumn(5).setMinWidth(150);
            tablaCurso.getColumnModel().getColumn(5).setMaxWidth(150);
            tablaCurso.getColumnModel().getColumn(6).setMaxWidth(150);
            tablaCurso.getColumnModel().getColumn(7).setMaxWidth(150);
            tablaCurso.getColumnModel().getColumn(8).setMaxWidth(150);
        }

        btnNuevoCurso.setBackground(new java.awt.Color(69, 167, 154));
        btnNuevoCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Add.png"))); // NOI18N
        btnNuevoCurso.setText("Nuevo");
        btnNuevoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoCursoActionPerformed(evt);
            }
        });

        txtBuscarCurso.setForeground(new java.awt.Color(69, 167, 154));
        txtBuscarCurso.setBorderColor(new java.awt.Color(255, 255, 255));
        txtBuscarCurso.setBotonColor(new java.awt.Color(69, 167, 154));
        txtBuscarCurso.setPhColor(new java.awt.Color(71, 120, 197));
        txtBuscarCurso.setPlaceholder("Buscar....");
        txtBuscarCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarCursoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarCursoKeyTyped(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editfind_104370.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);

        rSComboMetro1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buscar Por:", "Nombre", "Duración" }));
        rSComboMetro1.setColorArrow(new java.awt.Color(69, 167, 154));
        rSComboMetro1.setColorBorde(new java.awt.Color(69, 167, 154));
        rSComboMetro1.setColorFondo(new java.awt.Color(69, 167, 154));
        rSComboMetro1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(69, 167, 154));
        jSeparator1.setForeground(new java.awt.Color(69, 167, 154));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnNuevoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(txtBuscarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(rSComboMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnNuevoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBuscarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jButton1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(rSComboMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnNuevoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoCursoActionPerformed
        registroCurso reho = new registroCurso(new JFrame(), true);
        reho.setVisible(true);
    }//GEN-LAST:event_btnNuevoCursoActionPerformed

    private void btnEditarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCursoActionPerformed
        int fila = Cursos.tablaCurso.getSelectedRow();
         updateCursos mp3 = new updateCursos(new JFrame(), true);
         mp3.txtNombreCursoUP.setText(tablaCurso.getValueAt(fila, 1).toString());
         mp3.txtDuracionUp.setText(tablaCurso.getValueAt(fila, 2).toString());
         mp3.txtCuotasUp.setText(tablaCurso.getValueAt(fila, 3).toString());
         mp3.txtPreCuoUp.setText(tablaCurso.getValueAt(fila, 4).toString());
         mp3.txtPreTotUp.setText(tablaCurso.getValueAt(fila, 5).toString());
         mp3.lblIdCursoUp.setText(tablaCurso.getValueAt(fila, 0).toString());
         FuncionesAca.isListar("");
         mp3.setVisible(true);  
    }//GEN-LAST:event_btnEditarCursoActionPerformed

    private void btnEliminarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCursoActionPerformed
        int fila = tablaCurso.getSelectedRow();
        SentenciasAca s = new SentenciasAca();
        s.setID_CURSO(Cursos.tablaCurso.getValueAt(fila, 0).toString());
        if(JOptionPane.showConfirmDialog(this, "¿Desea Eliminar el Registro?","",
            JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
        if (FuncionesAca.isDelete(s)){
            FuncionesAca.isListar("");
               registroCurso.lblIdCurso.setText(FuncionesAca.extraerIDMax());
            JOptionPane.showMessageDialog(this, "Registro Eliminado con exito.", "Información", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Error al intentar eliminar el registro.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnEliminarCursoActionPerformed

    private void txtBuscarCursoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCursoKeyTyped
        char letras = evt.getKeyChar();
        if (Character.isLowerCase(letras)) {
            String cad = ("" + letras).toUpperCase();
            letras = cad.charAt(0);
            evt.setKeyChar(letras);
        }
    }//GEN-LAST:event_txtBuscarCursoKeyTyped

    private void txtBuscarCursoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCursoKeyReleased
       FuncionesAca.isListar(this.txtBuscarCurso.getText());
    }//GEN-LAST:event_txtBuscarCursoKeyReleased

    private void btnAgregarModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarModuloActionPerformed
        registoModulo remo = new registoModulo(new JFrame(), true);
        String nomCurso = "", id = "";
        int fila = tablaCurso.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningun dato");         
        }
        id =  (String)tablaCurso.getValueAt(fila, 0);
        nomCurso =  (String)tablaCurso.getValueAt(fila, 1);
        registoModulo.txtCursoMod.setText(nomCurso);
        registoModulo.lblIdCursoMOd.setText(id);
        jPopupMenuCurso.setVisible(false);
        remo.setVisible(true);
    }//GEN-LAST:event_btnAgregarModuloActionPerformed

    private void btnVerModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerModulosActionPerformed
       Modulos mo = new Modulos();
       nuevoPrincipal.panelEscritorio.add(mo);
       mo.setVisible(true);
    }//GEN-LAST:event_btnVerModulosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarModulo;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEditarCurso;
    private javax.swing.JButton btnEliminarCurso;
    private rojerusan.RSButtonIconI btnNuevoCurso;
    private javax.swing.JButton btnVerModulos;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenuCurso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menuCurso;
    private rojerusan.RSComboMetro rSComboMetro1;
    public static rojerusan.RSTableMetro tablaCurso;
    private rojerusan.RSMetroTextFullPlaceHolder txtBuscarCurso;
    // End of variables declaration//GEN-END:variables
}
