/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import academicos.FuncionesPuntajes;
import academicos.Puntajes;
import academicos.registroPuntajes;
import calificaciones.FuncionesCalificaiones;
import calificaciones.registroCalificacion;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import principal.FuncionesPrincipal;
import rojerusan.RSNotifyShadowAnimated;
import rojerusan.RSPanelsSlider;

/**
 *
 * @author Gustavo
 */
public class Clases extends javax.swing.JInternalFrame {

    /**
     * Creates new form Clases
     */
    public Clases() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        FuncionesClases.isCargarTablaFiltro();
        FuncionesPrincipal.cargarLista();
        jPopupMenu1.add(menuClases);
        rSPopuMenu1.add(menuList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuClases = new javax.swing.JPanel();
        btnEditarClase = new javax.swing.JButton();
        btnEliminarClase = new javax.swing.JButton();
        btnPuntajesAgrega = new javax.swing.JButton();
        btnVerPunt = new javax.swing.JButton();
        AgregarNota = new javax.swing.JButton();
        btnDetalleClaseVer = new javax.swing.JButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        rSPopuMenu1 = new rojerusan.RSPopuMenu();
        menuList = new javax.swing.JPanel();
        btnFiltrar = new rojerusan.RSButtonRound();
        clases = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClase = new rojerusan.RSTableMetro();
        btnNuevo = new rojerusan.RSButtonIconI();
        txtBuscarClase = new rojerusan.RSMetroTextFullPlaceHolder();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jcbFiltro = new rojerusan.RSComboMetro();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlistDocentes = new javax.swing.JList<>();
        btnMostrarTodo = new rojerusan.RSButtonRound();
        btnMostrarFiltro = new rojerusan.RSButtonRound();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rSButtonRound1 = new rojerusan.RSButtonRound();

        menuClases.setBackground(new java.awt.Color(255, 255, 255));

        btnEditarClase.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnEditarClase.setText("Editar");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        btnEditarClase.setBorder(dropShadowBorder1);
        btnEditarClase.setContentAreaFilled(false);
        btnEditarClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClaseActionPerformed(evt);
            }
        });

        btnEliminarClase.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnEliminarClase.setText("Eliminar");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        btnEliminarClase.setBorder(dropShadowBorder2);
        btnEliminarClase.setContentAreaFilled(false);
        btnEliminarClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClaseActionPerformed(evt);
            }
        });

        btnPuntajesAgrega.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnPuntajesAgrega.setText("Agregar Puntajes");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShowLeftShadow(true);
        dropShadowBorder3.setShowTopShadow(true);
        btnPuntajesAgrega.setBorder(dropShadowBorder3);
        btnPuntajesAgrega.setContentAreaFilled(false);
        btnPuntajesAgrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntajesAgregaActionPerformed(evt);
            }
        });

        btnVerPunt.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnVerPunt.setText("Ver Puntajes");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder4 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder4.setShowLeftShadow(true);
        dropShadowBorder4.setShowTopShadow(true);
        btnVerPunt.setBorder(dropShadowBorder4);
        btnVerPunt.setContentAreaFilled(false);
        btnVerPunt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPuntActionPerformed(evt);
            }
        });

        AgregarNota.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        AgregarNota.setText("Agregar Nota");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder5 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder5.setShowLeftShadow(true);
        dropShadowBorder5.setShowTopShadow(true);
        AgregarNota.setBorder(dropShadowBorder5);
        AgregarNota.setContentAreaFilled(false);
        AgregarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarNotaActionPerformed(evt);
            }
        });

        btnDetalleClaseVer.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnDetalleClaseVer.setText("Ver Detalle Clase");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder6 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder6.setShowLeftShadow(true);
        dropShadowBorder6.setShowTopShadow(true);
        btnDetalleClaseVer.setBorder(dropShadowBorder6);
        btnDetalleClaseVer.setContentAreaFilled(false);
        btnDetalleClaseVer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDetalleClaseVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleClaseVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuClasesLayout = new javax.swing.GroupLayout(menuClases);
        menuClases.setLayout(menuClasesLayout);
        menuClasesLayout.setHorizontalGroup(
            menuClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuClasesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditarClase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarClase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerPunt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AgregarNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menuClasesLayout.createSequentialGroup()
                        .addComponent(btnPuntajesAgrega)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnDetalleClaseVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuClasesLayout.setVerticalGroup(
            menuClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuClasesLayout.createSequentialGroup()
                .addComponent(btnEditarClase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarClase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDetalleClaseVer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPuntajesAgrega)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerPunt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AgregarNota))
        );

        menuList.setBackground(new java.awt.Color(255, 255, 255));

        btnFiltrar.setText("Filtrar por Modulo");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuListLayout = new javax.swing.GroupLayout(menuList);
        menuList.setLayout(menuListLayout);
        menuListLayout.setHorizontalGroup(
            menuListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuListLayout.setVerticalGroup(
            menuListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setMaximumSize(new java.awt.Dimension(1160, 690));
        setMinimumSize(new java.awt.Dimension(1160, 690));
        setPreferredSize(new java.awt.Dimension(1160, 690));
        setRequestFocusEnabled(false);

        clases.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder7 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder7.setShowLeftShadow(true);
        dropShadowBorder7.setShowTopShadow(true);
        clases.setBorder(dropShadowBorder7);
        clases.setMaximumSize(new java.awt.Dimension(1160, 647));
        clases.setMinimumSize(new java.awt.Dimension(1160, 647));
        clases.setName("clases"); // NOI18N
        clases.setPreferredSize(new java.awt.Dimension(1160, 647));

        tablaClase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " ", "Alumno", "Modulo", "Tema", "Actividad"
            }
        ));
        tablaClase.setColorBackgoundHead(new java.awt.Color(69, 167, 154));
        tablaClase.setColorBordeFilas(new java.awt.Color(69, 167, 154));
        tablaClase.setColorBordeHead(new java.awt.Color(69, 167, 154));
        tablaClase.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tablaClase.setColorFilasForeground1(new java.awt.Color(102, 102, 102));
        tablaClase.setColorFilasForeground2(new java.awt.Color(102, 102, 102));
        tablaClase.setColorSelBackgound(new java.awt.Color(69, 167, 154));
        tablaClase.setComponentPopupMenu(jPopupMenu1);
        tablaClase.setFuenteFilas(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        tablaClase.setFuenteFilasSelect(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        tablaClase.setFuenteHead(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tablaClase.setGridColor(new java.awt.Color(153, 153, 153));
        tablaClase.setGrosorBordeFilas(0);
        tablaClase.setSelectionBackground(new java.awt.Color(69, 167, 154));
        jScrollPane1.setViewportView(tablaClase);
        tablaClase.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tablaClase.getColumnModel().getColumnCount() > 0) {
            tablaClase.getColumnModel().getColumn(0).setMinWidth(10);
            tablaClase.getColumnModel().getColumn(0).setMaxWidth(20);
            tablaClase.getColumnModel().getColumn(1).setResizable(false);
        }

        btnNuevo.setBackground(new java.awt.Color(69, 167, 154));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Add.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        txtBuscarClase.setForeground(new java.awt.Color(69, 167, 154));
        txtBuscarClase.setBorderColor(new java.awt.Color(255, 255, 255));
        txtBuscarClase.setBotonColor(new java.awt.Color(69, 167, 154));
        txtBuscarClase.setPhColor(new java.awt.Color(69, 167, 154));
        txtBuscarClase.setPlaceholder("Buscar....");
        txtBuscarClase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarClaseKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarClaseKeyTyped(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editfind_104370.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);

        jSeparator1.setBackground(new java.awt.Color(69, 167, 154));
        jSeparator1.setForeground(new java.awt.Color(69, 167, 154));

        jcbFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buscar Por:", "Alumno", "Modulo" }));
        jcbFiltro.setColorArrow(new java.awt.Color(69, 167, 154));
        jcbFiltro.setColorBorde(new java.awt.Color(69, 167, 154));
        jcbFiltro.setColorFondo(new java.awt.Color(69, 167, 154));
        jcbFiltro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(69, 167, 154));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(69, 167, 154)));

        jlistDocentes.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(26, 145, 161), 3, true), "Lista de Docentes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(26, 145, 161))); // NOI18N
        jlistDocentes.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jlistDocentes.setToolTipText("");
        jlistDocentes.setComponentPopupMenu(rSPopuMenu1);
        jlistDocentes.setSelectionBackground(new java.awt.Color(69, 167, 154));
        jlistDocentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlistDocentesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jlistDocentes);

        btnMostrarTodo.setBackground(new java.awt.Color(255, 255, 255));
        btnMostrarTodo.setText("+");
        btnMostrarTodo.setColorText(new java.awt.Color(102, 102, 102));
        btnMostrarTodo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMostrarTodo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMostrarTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarTodoMouseClicked(evt);
            }
        });

        btnMostrarFiltro.setBackground(new java.awt.Color(255, 255, 255));
        btnMostrarFiltro.setForeground(new java.awt.Color(102, 102, 102));
        btnMostrarFiltro.setText("-");
        btnMostrarFiltro.setToolTipText("");
        btnMostrarFiltro.setColorText(new java.awt.Color(102, 102, 102));
        btnMostrarFiltro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMostrarFiltro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMostrarFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarFiltroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnMostrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMostrarFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(69, 167, 154));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 33));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Información de Clases");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 0, 267, 40));

        rSButtonRound1.setBackground(new java.awt.Color(69, 167, 154));
        rSButtonRound1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/closeWhite.png"))); // NOI18N
        rSButtonRound1.setColorHover(new java.awt.Color(255, 0, 0));
        rSButtonRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 40, -1));

        javax.swing.GroupLayout clasesLayout = new javax.swing.GroupLayout(clases);
        clases.setLayout(clasesLayout);
        clasesLayout.setHorizontalGroup(
            clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clasesLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clasesLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(298, 298, 298)
                        .addComponent(jcbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(clasesLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txtBuscarClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(clasesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        clasesLayout.setVerticalGroup(
            clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clasesLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clasesLayout.createSequentialGroup()
                        .addGroup(clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBuscarClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(clasesLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clases, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClaseActionPerformed
        int fila = tablaClase.getSelectedRow();
         updateClase upF = new updateClase(new JFrame(), true);
         upF.jcbDocentesUp.setSelectedItem(tablaClase.getValueAt(fila, 1).toString());
         upF.jcbAlumnosUp.setSelectedItem(tablaClase.getValueAt(fila, 2).toString());
         upF.jcbGabinetesUp.setSelectedItem(tablaClase.getValueAt(fila, 3).toString());
         upF.jcbHorarioUp.setSelectedItem(tablaClase.getValueAt(fila, 4).toString());
         //upF.jcbModulosUp.setSelectedItem(tablaClase.getValueAt(fila, 5).toString());
         upF.txtTemaUp.setText(tablaClase.getValueAt(fila, 6).toString());
         upF.txtActividadUp.setText(tablaClase.getValueAt(fila, 7).toString());
         upF.lblIDClasesUp.setText(tablaClase.getValueAt(fila, 0).toString());
         FuncionesClases.isCargarTablaFiltro();
         upF.setVisible(true);
    }//GEN-LAST:event_btnEditarClaseActionPerformed

    private void btnEliminarClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClaseActionPerformed
      int fila = tablaClase.getSelectedRow();
        SentenciasClases s = new SentenciasClases();
        s.setID_CLASE(tablaClase.getValueAt(fila, 0).toString());
        if(JOptionPane.showConfirmDialog(this, "¿Desea Eliminar el Registro?","",
            JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            if (FuncionesClases.isDelete(s)){
                FuncionesClases.isCargarTablaFiltro();
                 registroClases.lblIDClases.setText(FuncionesClases.extraerIDMax());
              //  JOptionPane.showMessageDialog(this, "Registro Eliminado con exito.", "Información", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Error al intentar eliminar el registro.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarClaseActionPerformed

    private void btnPuntajesAgregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntajesAgregaActionPerformed
        registroPuntajes regIns = new registroPuntajes(new JFrame(), true);
        String name = "", id = "";
        int fila = tablaClase.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningun dato");         
        }
         id =  (String)tablaClase.getValueAt(fila, 0);
         name = (String) tablaClase.getValueAt(fila, 1);
         registroPuntajes.txtAlumno.setText(name);
         registroPuntajes.idClase.setText(id);
         registroPuntajes.txtAlumno.setEnabled(false);
         jPopupMenu1.setVisible(false);
         regIns.setVisible(true);
    }//GEN-LAST:event_btnPuntajesAgregaActionPerformed

    private void btnMostrarFiltroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarFiltroMouseClicked
        FuncionesClases.isCargarTablaFiltro();
    }//GEN-LAST:event_btnMostrarFiltroMouseClicked

    private void btnMostrarTodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarTodoMouseClicked
        FuncionesClases.isCargarTablaTodo();
    }//GEN-LAST:event_btnMostrarTodoMouseClicked

    private void txtBuscarClaseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarClaseKeyTyped
        char letras = evt.getKeyChar();
        //  FuncionesClases.isCargarTablaFiltro();
        if (Character.isLowerCase(letras)) {
            String cad = ("" + letras).toUpperCase();
            letras = cad.charAt(0);
            evt.setKeyChar(letras);
        }
    }//GEN-LAST:event_txtBuscarClaseKeyTyped

    private void txtBuscarClaseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarClaseKeyReleased
        FuncionesClases.isBuscarDatos(txtBuscarClase.getText(), jcbFiltro.getSelectedItem().toString());
    }//GEN-LAST:event_txtBuscarClaseKeyReleased

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        registroClases redo = new registroClases(new JFrame(), true);
        redo.setVisible(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnVerPuntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPuntActionPerformed
        puntajesAlumnos pun = new puntajesAlumnos(new JFrame(), true);
        String name = "", id = "";
        int fila = tablaClase.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningun dato");         
        }
         name = (String) tablaClase.getValueAt(fila, 1);
         FuncionesPuntajes.mostrarPuntajeAlumno(name);
        jPopupMenu1.setVisible(false);
        pun.setVisible(true);
    }//GEN-LAST:event_btnVerPuntActionPerformed

    private void AgregarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarNotaActionPerformed
        registroCalificacion reCali = new registroCalificacion(new JFrame(), true);
        String name = "", modulo="";
        int fila = tablaClase.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningun dato");         
        }
        name = (String) tablaClase.getValueAt(fila, 1);
        modulo = (String) tablaClase.getValueAt(fila, 2);
        FuncionesCalificaiones.mostrarPuntajeAlumno(name);
        FuncionesCalificaiones.isModulo(modulo);
        jPopupMenu1.setVisible(false);
        reCali.setVisible(true);
    }//GEN-LAST:event_AgregarNotaActionPerformed

    private void rSButtonRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound1ActionPerformed
       dispose();
    }//GEN-LAST:event_rSButtonRound1ActionPerformed

    private void jlistDocentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlistDocentesMouseClicked
      Integer list = Clases.jlistDocentes.getSelectedIndex()+1;
       if(list==0){
           new rojerusan.RSNotifyShadowAnimated("Oops!", "Falta Seleccionar el Docente", 5, RSNotifyShadowAnimated.PositionNotify.TopLef, RSNotifyShadowAnimated.AnimationNotify.UpBottom, RSNotifyShadowAnimated.TypeNotify.WARNING).setVisible(true);
       }else {
            FuncionesClases.filtroDocente(list);
       }
    }//GEN-LAST:event_jlistDocentesMouseClicked

    private void btnDetalleClaseVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleClaseVerActionPerformed
        detalleClase detCla = new detalleClase(new JFrame(), true);
        String name = "";
        int fila = tablaClase.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningun dato");         
        }
        name = (String) tablaClase.getValueAt(fila, 1);
        FuncionesClases.mostrarDetalleClase(name);
        jPopupMenu1.setVisible(false);
        detalleClase.lblDetClaseAlumno.setText(name);
        detCla.setVisible(true);
    }//GEN-LAST:event_btnDetalleClaseVerActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        filtroDocentesModulo filDOc = new filtroDocentesModulo(new JFrame(), true);
        FuncionesClases.cargarCursosdeDocentes(FuncionesClases.idDOCENTES);
        filDOc.setLocation(10, 10);
        filDOc.setVisible(true);
        rSPopuMenu1.setVisible(false);
    }//GEN-LAST:event_btnFiltrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarNota;
    private javax.swing.JButton btnDetalleClaseVer;
    private javax.swing.JButton btnEditarClase;
    private javax.swing.JButton btnEliminarClase;
    private rojerusan.RSButtonRound btnFiltrar;
    private rojerusan.RSButtonRound btnMostrarFiltro;
    private rojerusan.RSButtonRound btnMostrarTodo;
    private rojerusan.RSButtonIconI btnNuevo;
    private javax.swing.JButton btnPuntajesAgrega;
    private javax.swing.JButton btnVerPunt;
    private javax.swing.JPanel clases;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private rojerusan.RSComboMetro jcbFiltro;
    public static javax.swing.JList<String> jlistDocentes;
    private javax.swing.JPanel menuClases;
    private javax.swing.JPanel menuList;
    private rojerusan.RSButtonRound rSButtonRound1;
    private rojerusan.RSPopuMenu rSPopuMenu1;
    public static rojerusan.RSTableMetro tablaClase;
    private rojerusan.RSMetroTextFullPlaceHolder txtBuscarClase;
    // End of variables declaration//GEN-END:variables
}
