/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import javax.swing.JOptionPane;
import librerias.ClaseValidaciones;
import librerias.LetrasMayusculas;

/**
 *
 * @author Gustavo
 */
public class updateClase extends javax.swing.JDialog {

    /**
     * Creates new form updateClase
     */
    public updateClase(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        FuncionesClases.isCargarAlumnosUp();
        FuncionesClases.isCargarDocentesUp();
        FuncionesClases.isCargarGabineteUp();
        FuncionesClases.isCargarHorarioUp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelShadow1 = new org.edisoncor.gui.panel.PanelShadow();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        panelRectTranslucido1 = new org.edisoncor.gui.panel.PanelRectTranslucido();
        jLabel3 = new javax.swing.JLabel();
        btnActualizarClases = new javax.swing.JButton();
        lblIDClasesUp = new javax.swing.JLabel();
        txtTemaUp = new rojerusan.RSMetroTextFullPlaceHolder();
        txtActividadUp = new rojerusan.RSMetroTextFullPlaceHolder();
        jcbDocentesUp = new rojerusan.RSComboMetro();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcbGabinetesUp = new rojerusan.RSComboMetro();
        jLabel12 = new javax.swing.JLabel();
        jcbHorarioUp = new rojerusan.RSComboMetro();
        idAlumnUp = new javax.swing.JLabel();
        jcbAlumnosUp = new rojerusan.RSComboMetro();
        lblError = new javax.swing.JLabel();
        idDocenteUp = new javax.swing.JLabel();
        txtFechaClase = new rojerusan.RSDateChooser();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(69, 167, 154));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        jPanel1.setBorder(dropShadowBorder1);

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setCornerSize(20);
        dropShadowBorder2.setShadowOpacity(0.7F);
        dropShadowBorder2.setShadowSize(7);
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        panelShadow1.setBorder(dropShadowBorder2);

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Clases.");

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        btnCerrar.setToolTipText("Cerrar");
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 565, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow1Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addComponent(btnCerrar)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelRectTranslucido1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Gadugi", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panelRectTranslucido1.setColorDeBorde(new java.awt.Color(69, 167, 154));
        panelRectTranslucido1.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Docente:");

        btnActualizarClases.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        btnActualizarClases.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarClases.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Save_48px.png"))); // NOI18N
        btnActualizarClases.setText("Actualizar");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShowLeftShadow(true);
        dropShadowBorder3.setShowTopShadow(true);
        btnActualizarClases.setBorder(dropShadowBorder3);
        btnActualizarClases.setContentAreaFilled(false);
        btnActualizarClases.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizarClases.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActualizarClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarClasesActionPerformed(evt);
            }
        });

        lblIDClasesUp.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblIDClasesUp.setForeground(new java.awt.Color(255, 255, 255));
        lblIDClasesUp.setText(" ");

        txtTemaUp.setForeground(new java.awt.Color(69, 167, 154));
        txtTemaUp.setBorderColor(new java.awt.Color(69, 167, 154));
        txtTemaUp.setBotonColor(new java.awt.Color(69, 167, 154));
        txtTemaUp.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        txtTemaUp.setMaximumSize(new java.awt.Dimension(250, 42));
        txtTemaUp.setMinimumSize(new java.awt.Dimension(250, 42));
        txtTemaUp.setPhColor(new java.awt.Color(71, 120, 197));
        txtTemaUp.setPlaceholder("Escribe si o no");
        txtTemaUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemaUpActionPerformed(evt);
            }
        });
        txtTemaUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTemaUpKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTemaUpKeyTyped(evt);
            }
        });

        txtActividadUp.setForeground(new java.awt.Color(69, 167, 154));
        txtActividadUp.setBorderColor(new java.awt.Color(69, 167, 154));
        txtActividadUp.setBotonColor(new java.awt.Color(69, 167, 154));
        txtActividadUp.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        txtActividadUp.setPhColor(new java.awt.Color(71, 120, 197));
        txtActividadUp.setPlaceholder("Escribe si o no");
        txtActividadUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActividadUpActionPerformed(evt);
            }
        });
        txtActividadUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtActividadUpKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtActividadUpKeyTyped(evt);
            }
        });

        jcbDocentesUp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        jcbDocentesUp.setColorArrow(new java.awt.Color(69, 167, 154));
        jcbDocentesUp.setColorBorde(new java.awt.Color(69, 167, 154));
        jcbDocentesUp.setColorFondo(new java.awt.Color(69, 167, 154));
        jcbDocentesUp.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        jcbDocentesUp.setMaximumSize(new java.awt.Dimension(250, 42));
        jcbDocentesUp.setMinimumSize(new java.awt.Dimension(250, 42));
        jcbDocentesUp.setPreferredSize(new java.awt.Dimension(250, 42));
        jcbDocentesUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDocentesUpActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tema:");

        jLabel7.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Alumno:");

        jLabel9.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Actividad:");

        jLabel11.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Gabinete:");

        jcbGabinetesUp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        jcbGabinetesUp.setColorArrow(new java.awt.Color(69, 167, 154));
        jcbGabinetesUp.setColorBorde(new java.awt.Color(69, 167, 154));
        jcbGabinetesUp.setColorFondo(new java.awt.Color(69, 167, 154));
        jcbGabinetesUp.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        jcbGabinetesUp.setMaximumSize(new java.awt.Dimension(250, 42));
        jcbGabinetesUp.setMinimumSize(new java.awt.Dimension(250, 42));
        jcbGabinetesUp.setPreferredSize(new java.awt.Dimension(250, 42));
        jcbGabinetesUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbGabinetesUpActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Horario:");

        jcbHorarioUp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        jcbHorarioUp.setColorArrow(new java.awt.Color(69, 167, 154));
        jcbHorarioUp.setColorBorde(new java.awt.Color(69, 167, 154));
        jcbHorarioUp.setColorFondo(new java.awt.Color(69, 167, 154));
        jcbHorarioUp.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        jcbHorarioUp.setMaximumSize(new java.awt.Dimension(250, 42));
        jcbHorarioUp.setMinimumSize(new java.awt.Dimension(250, 42));
        jcbHorarioUp.setPreferredSize(new java.awt.Dimension(250, 42));
        jcbHorarioUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHorarioUpActionPerformed(evt);
            }
        });

        idAlumnUp.setForeground(new java.awt.Color(255, 255, 255));
        idAlumnUp.setText(" ");

        jcbAlumnosUp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        jcbAlumnosUp.setColorArrow(new java.awt.Color(69, 167, 154));
        jcbAlumnosUp.setColorBorde(new java.awt.Color(69, 167, 154));
        jcbAlumnosUp.setColorFondo(new java.awt.Color(69, 167, 154));
        jcbAlumnosUp.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        jcbAlumnosUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAlumnosUpActionPerformed(evt);
            }
        });
        jcbAlumnosUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcbAlumnosUpKeyReleased(evt);
            }
        });

        lblError.setForeground(new java.awt.Color(255, 255, 255));

        idDocenteUp.setForeground(new java.awt.Color(255, 255, 255));
        idDocenteUp.setText("  ");

        txtFechaClase.setColorBackground(new java.awt.Color(69, 167, 154));
        txtFechaClase.setFormatoFecha("dd/MM/yyyy");

        jLabel10.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fecha:");

        javax.swing.GroupLayout panelRectTranslucido1Layout = new javax.swing.GroupLayout(panelRectTranslucido1);
        panelRectTranslucido1.setLayout(panelRectTranslucido1Layout);
        panelRectTranslucido1Layout.setHorizontalGroup(
            panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jLabel12))
                                .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel11)))
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbAlumnosUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbGabinetesUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbHorarioUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbDocentesUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel10))
                        .addGap(32, 32, 32)
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechaClase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTemaUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtActividadUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRectTranslucido1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRectTranslucido1Layout.createSequentialGroup()
                                .addComponent(btnActualizarClases, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(247, 247, 247)
                                .addComponent(idDocenteUp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idAlumnUp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIDClasesUp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelRectTranslucido1Layout.setVerticalGroup(
            panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRectTranslucido1Layout.createSequentialGroup()
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTemaUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtActividadUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRectTranslucido1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbAlumnosUp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbDocentesUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbGabinetesUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addGap(18, 18, 18)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbHorarioUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel10))
                    .addComponent(txtFechaClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIDClasesUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idAlumnUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idDocenteUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnActualizarClases))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelRectTranslucido1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRectTranslucido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnActualizarClasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarClasesActionPerformed
        try {
          if(txtTemaUp.getText().equals("") || txtActividadUp.getText().equals("") || jcbAlumnosUp.getSelectedIndex()==0 || jcbDocentesUp.getSelectedIndex()==0
                  ||jcbGabinetesUp.getSelectedIndex()==0 || jcbHorarioUp.getSelectedIndex()==0){
            lblError.setText("TODOS LOS CAMPOS SON OBLIGATORIOS");
          }else{
               SentenciasClases s = new SentenciasClases();
            s.setID_DOCENTE(jcbDocentesUp.getSelectedIndex());
            s.setID_ALUMNO(Integer.parseInt(idAlumnUp.getText()));
            s.setID_GABINETE(jcbGabinetesUp.getSelectedIndex());
            s.setID_HORARIO(jcbHorarioUp.getSelectedIndex());
           // s.setID_MODULO(jcbModulosUp.getSelectedIndex());
            s.setTEMA(txtTemaUp.getText());
            s.setACTIVIDAD(txtActividadUp.getText());
            s.setID_CLASE(lblIDClasesUp.getText());
                if(FuncionesClases.isUpdate(s)){
                    FuncionesClases.isCargarTablaFiltro();
                    dispose();
                    JOptionPane.showMessageDialog(this, "Se Actualizó Correctamente.", "Información", JOptionPane.INFORMATION_MESSAGE);
                }else{
                     JOptionPane.showMessageDialog(this, "Error al intentar Guardar.", "ERROR", JOptionPane.ERROR_MESSAGE);
              }
            }  
        } catch (Exception ex) {
            System.out.println("error:" + ex.getMessage());
        }
    }//GEN-LAST:event_btnActualizarClasesActionPerformed

    private void txtTemaUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemaUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemaUpActionPerformed

    private void txtTemaUpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTemaUpKeyReleased
        LetrasMayusculas.convertiraMayusculas(txtTemaUp);
    }//GEN-LAST:event_txtTemaUpKeyReleased

    private void txtTemaUpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTemaUpKeyTyped
        if(txtTemaUp.getText().length()>=25){
            evt.consume();
        }
        // validar solo letras
        if(ClaseValidaciones.Letras(evt.getKeyChar()) && (ClaseValidaciones.Espacio(evt.getKeyChar()))){
            evt.consume();
        }
    }//GEN-LAST:event_txtTemaUpKeyTyped

    private void txtActividadUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActividadUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActividadUpActionPerformed

    private void txtActividadUpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtActividadUpKeyReleased
        LetrasMayusculas.convertiraMayusculas(txtActividadUp);
    }//GEN-LAST:event_txtActividadUpKeyReleased

    private void txtActividadUpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtActividadUpKeyTyped
        if(txtActividadUp.getText().length()>=25){
            evt.consume();
        }
        // validar solo letras
        if(ClaseValidaciones.Letras(evt.getKeyChar()) && (ClaseValidaciones.Espacio(evt.getKeyChar()))){
            evt.consume();
        }
    }//GEN-LAST:event_txtActividadUpKeyTyped

    private void jcbDocentesUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDocentesUpActionPerformed
        //   FuncionesClases.isDocentes();
    }//GEN-LAST:event_jcbDocentesUpActionPerformed

    private void jcbGabinetesUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbGabinetesUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbGabinetesUpActionPerformed

    private void jcbHorarioUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHorarioUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbHorarioUpActionPerformed

    private void jcbAlumnosUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAlumnosUpActionPerformed
        FuncionesClases.isAlumnosUp();
    }//GEN-LAST:event_jcbAlumnosUpActionPerformed

    private void jcbAlumnosUpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbAlumnosUpKeyReleased

    }//GEN-LAST:event_jcbAlumnosUpKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                updateClase dialog = new updateClase(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarClases;
    private javax.swing.JButton btnCerrar;
    public static javax.swing.JLabel idAlumnUp;
    public static javax.swing.JLabel idDocenteUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static rojerusan.RSComboMetro jcbAlumnosUp;
    public static rojerusan.RSComboMetro jcbDocentesUp;
    public static rojerusan.RSComboMetro jcbGabinetesUp;
    public static rojerusan.RSComboMetro jcbHorarioUp;
    public static javax.swing.JLabel lblError;
    public static javax.swing.JLabel lblIDClasesUp;
    public static org.edisoncor.gui.panel.PanelRectTranslucido panelRectTranslucido1;
    private org.edisoncor.gui.panel.PanelShadow panelShadow1;
    public static rojerusan.RSMetroTextFullPlaceHolder txtActividadUp;
    private rojerusan.RSDateChooser txtFechaClase;
    public static rojerusan.RSMetroTextFullPlaceHolder txtTemaUp;
    // End of variables declaration//GEN-END:variables
}
