
package proveedores;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import librerias.ClaseValidaciones;
import principal.FuncionesPrincipal;
import principal.nuevoPrincipal;
import rojerusan.RSNotifyFade;

/**
 *
 * @author Gustavo
 */
public class updateProveedor extends javax.swing.JDialog {

    /**
     * Creates new form updateProveedor
     */
    public updateProveedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        FuncionesProveedor.isCargarProUp();
        lblIdProUp.setText(FuncionesProveedor.extraerIDMax());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelShadow1 = new org.edisoncor.gui.panel.PanelShadow();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        panelRectTranslucido1 = new org.edisoncor.gui.panel.PanelRectTranslucido();
        txtNomProUp = new rojerusan.RSMetroTextFullPlaceHolder();
        txtRucProUp = new rojerusan.RSMetroTextFullPlaceHolder();
        txtApeProUp = new rojerusan.RSMetroTextFullPlaceHolder();
        txtDirecPro = new rojerusan.RSMetroTextFullPlaceHolder();
        txtEmailProUP = new rojerusan.RSMetroTextFullPlaceHolder();
        txtCeluProUp = new rojerusan.RSMetroTextFullPlaceHolder();
        jcbCiudadesProUp = new rojerusan.RSComboMetro();
        jLabel3 = new javax.swing.JLabel();
        lblIdProUp = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtGuardarProv = new javax.swing.JButton();
        txtCedulaProUp = new rojerusan.RSMetroTextFullPlaceHolder();
        jLabel12 = new javax.swing.JLabel();
        lblErrorUp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(69, 167, 154));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        jPanel1.setBorder(dropShadowBorder1);

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setCornerSize(20);
        dropShadowBorder2.setShadowOpacity(0.7F);
        dropShadowBorder2.setShadowSize(7);
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        panelShadow1.setBorder(dropShadowBorder2);

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Proveedores.");

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        btnCerrar.setToolTipText("Cerrar");
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow1Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addComponent(btnCerrar)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelRectTranslucido1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Gadugi", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panelRectTranslucido1.setColorDeBorde(new java.awt.Color(69, 167, 154));
        panelRectTranslucido1.setOpaque(false);

        txtNomProUp.setForeground(new java.awt.Color(69, 167, 154));
        txtNomProUp.setBorderColor(new java.awt.Color(69, 167, 154));
        txtNomProUp.setBotonColor(new java.awt.Color(69, 167, 154));
        txtNomProUp.setPhColor(new java.awt.Color(71, 120, 197));
        txtNomProUp.setPlaceholder("Escribe si o no");
        txtNomProUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomProUpActionPerformed(evt);
            }
        });
        txtNomProUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomProUpKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomProUpKeyTyped(evt);
            }
        });

        txtRucProUp.setForeground(new java.awt.Color(69, 167, 154));
        txtRucProUp.setBorderColor(new java.awt.Color(69, 167, 154));
        txtRucProUp.setBotonColor(new java.awt.Color(69, 167, 154));
        txtRucProUp.setPhColor(new java.awt.Color(71, 120, 197));
        txtRucProUp.setPlaceholder("Escribe si o no");
        txtRucProUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRucProUpActionPerformed(evt);
            }
        });
        txtRucProUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRucProUpKeyTyped(evt);
            }
        });

        txtApeProUp.setForeground(new java.awt.Color(69, 167, 154));
        txtApeProUp.setBorderColor(new java.awt.Color(69, 167, 154));
        txtApeProUp.setBotonColor(new java.awt.Color(69, 167, 154));
        txtApeProUp.setPhColor(new java.awt.Color(71, 120, 197));
        txtApeProUp.setPlaceholder("Escribe si o no");
        txtApeProUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApeProUpActionPerformed(evt);
            }
        });
        txtApeProUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApeProUpKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApeProUpKeyTyped(evt);
            }
        });

        txtDirecPro.setForeground(new java.awt.Color(69, 167, 154));
        txtDirecPro.setBorderColor(new java.awt.Color(69, 167, 154));
        txtDirecPro.setBotonColor(new java.awt.Color(69, 167, 154));
        txtDirecPro.setPhColor(new java.awt.Color(71, 120, 197));
        txtDirecPro.setPlaceholder("Escribe si o no");
        txtDirecPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirecProActionPerformed(evt);
            }
        });
        txtDirecPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDirecProKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDirecProKeyTyped(evt);
            }
        });

        txtEmailProUP.setForeground(new java.awt.Color(69, 167, 154));
        txtEmailProUP.setBorderColor(new java.awt.Color(69, 167, 154));
        txtEmailProUP.setBotonColor(new java.awt.Color(69, 167, 154));
        txtEmailProUP.setPhColor(new java.awt.Color(71, 120, 197));
        txtEmailProUP.setPlaceholder("Escribe si o no");
        txtEmailProUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailProUPActionPerformed(evt);
            }
        });
        txtEmailProUP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailProUPKeyTyped(evt);
            }
        });

        txtCeluProUp.setForeground(new java.awt.Color(69, 167, 154));
        txtCeluProUp.setBorderColor(new java.awt.Color(69, 167, 154));
        txtCeluProUp.setBotonColor(new java.awt.Color(69, 167, 154));
        txtCeluProUp.setPhColor(new java.awt.Color(71, 120, 197));
        txtCeluProUp.setPlaceholder("Escribe si o no");
        txtCeluProUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCeluProUpKeyTyped(evt);
            }
        });

        jcbCiudadesProUp.setColorArrow(new java.awt.Color(69, 167, 154));
        jcbCiudadesProUp.setColorBorde(new java.awt.Color(69, 167, 154));
        jcbCiudadesProUp.setColorFondo(new java.awt.Color(69, 167, 154));
        jcbCiudadesProUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCiudadesProUpActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");

        lblIdProUp.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblIdProUp.setForeground(new java.awt.Color(255, 255, 255));
        lblIdProUp.setText("ID");

        jLabel6.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ruc:");

        jLabel7.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Apellido:");

        jLabel8.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email:");

        jLabel9.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Dirección:");

        jLabel10.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("N° Celular:");

        jLabel11.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ciudad:");

        txtGuardarProv.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        txtGuardarProv.setForeground(new java.awt.Color(255, 255, 255));
        txtGuardarProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Save_48px.png"))); // NOI18N
        txtGuardarProv.setText("Actualizar");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShowLeftShadow(true);
        dropShadowBorder3.setShowTopShadow(true);
        txtGuardarProv.setBorder(dropShadowBorder3);
        txtGuardarProv.setContentAreaFilled(false);
        txtGuardarProv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtGuardarProv.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        txtGuardarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuardarProvActionPerformed(evt);
            }
        });

        txtCedulaProUp.setForeground(new java.awt.Color(69, 167, 154));
        txtCedulaProUp.setBorderColor(new java.awt.Color(69, 167, 154));
        txtCedulaProUp.setBotonColor(new java.awt.Color(69, 167, 154));
        txtCedulaProUp.setPhColor(new java.awt.Color(71, 120, 197));
        txtCedulaProUp.setPlaceholder("Escribe si o no");
        txtCedulaProUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaProUpActionPerformed(evt);
            }
        });
        txtCedulaProUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaProUpKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cedula:");

        lblErrorUp.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        lblErrorUp.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelRectTranslucido1Layout = new javax.swing.GroupLayout(panelRectTranslucido1);
        panelRectTranslucido1.setLayout(panelRectTranslucido1Layout);
        panelRectTranslucido1Layout.setHorizontalGroup(
            panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(txtGuardarProv, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234)
                .addComponent(lblIdProUp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblErrorUp, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApeProUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomProUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbCiudadesProUp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCeluProUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRectTranslucido1Layout.createSequentialGroup()
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(31, 31, 31)
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRucProUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDirecPro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailProUP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRectTranslucido1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(31, 31, 31)
                        .addComponent(txtCedulaProUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelRectTranslucido1Layout.setVerticalGroup(
            panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomProUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRucProUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApeProUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtDirecPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCiudadesProUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtEmailProUP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCedulaProUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCeluProUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addGap(28, 28, 28)
                .addComponent(lblErrorUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRectTranslucido1Layout.createSequentialGroup()
                        .addComponent(lblIdProUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRectTranslucido1Layout.createSequentialGroup()
                        .addComponent(txtGuardarProv)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRectTranslucido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRectTranslucido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtNomProUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomProUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomProUpActionPerformed

    private void txtRucProUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRucProUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRucProUpActionPerformed

    private void txtApeProUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApeProUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApeProUpActionPerformed

    private void txtDirecProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirecProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirecProActionPerformed

    private void txtEmailProUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailProUPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailProUPActionPerformed

    private void jcbCiudadesProUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCiudadesProUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCiudadesProUpActionPerformed

    private void txtCedulaProUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaProUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaProUpActionPerformed

    private void txtGuardarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuardarProvActionPerformed
        String tabla="PROVEEDORES", evento="UPDATE", hora=nuevoPrincipal.lblHora.getText(), fecha=nuevoPrincipal.lblFechaAc.getText();
        try {
           if(txtNomProUp.getText().equals("") || txtApeProUp.getText().equals("")
          || txtDirecPro.getText().equals("") || txtEmailProUP.getText().equals("")){
            lblErrorUp.setText("TODOS LOS CAMPOS SON OBLIGATORIOS");
          }else{
            SentenciasProveedor s = new SentenciasProveedor();
            s.setID_CIUDAD(jcbCiudadesProUp.getSelectedIndex());
            s.setNOM_PRO(txtNomProUp.getText());
            s.setAPE_PRO(txtApeProUp.getText());
            s.setRUC_PRO(txtRucProUp.getText());
            s.setCEDU_PRO(txtCedulaProUp.getText());
            s.setDREC_PRO(txtDirecPro.getText());
            s.setEMAIL_PRO(txtEmailProUP.getText());
            s.setCELU_PRO(txtCeluProUp.getText());
            s.setID_PROVEEDOR(lblIdProUp.getText());
                if(FuncionesProveedor.isUpdate(s)){
                    FuncionesProveedor.iscargarTabla("");
                    //lblIdProUp.setText(FuncionesProveedor.extraerIDMax());
                    FuncionesPrincipal.auditorias(login.Login.idUsu, hora, evento, tabla, fecha);
                    dispose();
                    new rojerusan.RSNotifyFade("¡HECHO!", "Se Actualizo Correctamente", 3, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
                }else{
                new rojerusan.RSNotifyFade("¡ERROR!", "No se pudo guardar", 3, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.ERROR).setVisible(true);
              }
            }  
        } catch (HeadlessException ex) {
            System.out.println("error:" + ex.getMessage());
        }
    }//GEN-LAST:event_txtGuardarProvActionPerformed

    private void txtNomProUpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomProUpKeyReleased
        librerias.LetrasMayusculas.convertiraMayusculas(txtNomProUp);
    }//GEN-LAST:event_txtNomProUpKeyReleased

    private void txtApeProUpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApeProUpKeyReleased
       librerias.LetrasMayusculas.convertiraMayusculas(txtApeProUp);
    }//GEN-LAST:event_txtApeProUpKeyReleased

    private void txtDirecProKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirecProKeyReleased
       librerias.LetrasMayusculas.convertiraMayusculas(txtDirecPro);
    }//GEN-LAST:event_txtDirecProKeyReleased

    private void txtNomProUpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomProUpKeyTyped
        if(txtNomProUp.getText().length()>=25){
            evt.consume();
        }
        // validar solo letras
        if(ClaseValidaciones.Letras(evt.getKeyChar()) && ClaseValidaciones.Espacio(evt.getKeyChar()) ){
            evt.consume();
           
        }
    }//GEN-LAST:event_txtNomProUpKeyTyped

    private void txtApeProUpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApeProUpKeyTyped
        if(txtApeProUp.getText().length()>=25){
            evt.consume();
        }
        // validar solo letras
        if(ClaseValidaciones.Letras(evt.getKeyChar()) && ClaseValidaciones.Espacio(evt.getKeyChar()) ){
            evt.consume();
           
        }
    }//GEN-LAST:event_txtApeProUpKeyTyped

    private void txtCeluProUpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCeluProUpKeyTyped
         if(txtCeluProUp.getText().length()>=25){
            evt.consume();
        }
        // validar solo letras
        if(ClaseValidaciones.Numeros(evt.getKeyChar())){
            evt.consume();
           
        }
    }//GEN-LAST:event_txtCeluProUpKeyTyped

    private void txtRucProUpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucProUpKeyTyped
        if(txtRucProUp.getText().length()>=25){
            evt.consume();
        }
        // validar solo letras
        if(ClaseValidaciones.Numeros(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtRucProUpKeyTyped

    private void txtDirecProKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirecProKeyTyped
        if(txtDirecPro.getText().length()>=25){
            evt.consume();
        }
        // validar solo letras
        if(ClaseValidaciones.ParaDireccion(evt.getKeyChar()) && ClaseValidaciones.Espacio(evt.getKeyChar()) ){
            evt.consume();  
        }
    }//GEN-LAST:event_txtDirecProKeyTyped

    private void txtEmailProUPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailProUPKeyTyped
       if(txtEmailProUP.getText().length()>=25){
            evt.consume();
        }
        // validar solo letras
        if(ClaseValidaciones.USU(evt.getKeyChar())){
            evt.consume();
           
        }
    }//GEN-LAST:event_txtEmailProUPKeyTyped

    private void txtCedulaProUpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaProUpKeyTyped
        if(txtCedulaProUp.getText().length()>=25){
            evt.consume();
        }
        // validar solo letras
        if(ClaseValidaciones.Cedula(evt.getKeyChar())){
            evt.consume();
           
        }
    }//GEN-LAST:event_txtCedulaProUpKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                updateProveedor dialog = new updateProveedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static rojerusan.RSComboMetro jcbCiudadesProUp;
    private javax.swing.JLabel lblErrorUp;
    public static javax.swing.JLabel lblIdProUp;
    public static org.edisoncor.gui.panel.PanelRectTranslucido panelRectTranslucido1;
    private org.edisoncor.gui.panel.PanelShadow panelShadow1;
    public static rojerusan.RSMetroTextFullPlaceHolder txtApeProUp;
    public static rojerusan.RSMetroTextFullPlaceHolder txtCedulaProUp;
    public static rojerusan.RSMetroTextFullPlaceHolder txtCeluProUp;
    public static rojerusan.RSMetroTextFullPlaceHolder txtDirecPro;
    public static rojerusan.RSMetroTextFullPlaceHolder txtEmailProUP;
    private javax.swing.JButton txtGuardarProv;
    public static rojerusan.RSMetroTextFullPlaceHolder txtNomProUp;
    public static rojerusan.RSMetroTextFullPlaceHolder txtRucProUp;
    // End of variables declaration//GEN-END:variables
}
